import { createElement } from 'react';
import type { ComponentType, SVGProps } from 'react';

import {
  IconAdjustmentsHorizontal,
  IconAlertTriangle,
  IconArrowBackUp,
  IconArrowElbowRight,
  IconArrowForwardUp,
  IconArrowLeft,
  IconCornerDownRight,
  IconArrowRight,
  IconArrowsRightLeft,
  IconArrowsSplit2,
  IconArrowUp,
  IconBolt,
  IconBoltFilled,
  IconBook2,
  IconBookmark,
  IconBookmarkPlus,
  IconBold,
  IconBoxMultiple,
  IconBrain,
  IconBrandFigma,
  IconBrandGithub,
  IconBrandGithubFilled,
  IconBrandGmail,
  IconBrandGoogleDrive,
  IconBrandNotion,
  IconBrandOpenai,
  IconBrandSlack,
  IconBrandTwitter,
  IconBrandVercel,
  IconBrandX,
  IconBug,
  IconCalendar,
  IconCamera,
  IconChartColumn,
  IconCheck,
  IconCheckbox,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircle,
  IconCircleCheck,
  IconCircleDashed,
  IconCircleX,
  IconClock,
  IconCloudUpload,
  IconCode,
  IconColumns2,
  IconCopy,
  IconDeviceDesktop,
  IconDeviceFloppy,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileDiff,
  IconFilePlus,
  IconFiles,
  IconFileText,
  IconFolder,
  IconFolderCode,
  IconFolderOpen,
  IconFolderPlus,
  IconFolderSearch,
  IconGauge,
  IconGitBranch,
  IconGitCommit,
  IconGitFork,
  IconGitPullRequest,
  IconH1,
  IconH2,
  IconH3,
  IconHash,
  IconItalic,
  IconLayoutGrid,
  IconLayoutSidebarRight,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
  IconLink,
  IconList,
  IconListCheck,
  IconListDetails,
  IconListNumbers,
  IconLoader2,
  IconMaximize,
  IconMessage,
  IconMessageCircle,
  IconMinimize,
  IconMinus,
  IconMoon,
  IconPalette,
  IconPaperclip,
  IconPencil,
  IconPencilPlus,
  IconPhoto,
  IconPin,
  IconPlayerPlay,
  IconPlug,
  IconPlugConnected,
  IconPlus,
  IconQuote,
  IconRefresh,
  IconRobot,
  IconHistory,
  IconRotateClockwise2,
  IconScript,
  IconSearch,
  IconServer,
  IconSettings,
  IconShieldCheck,
  IconShieldExclamation,
  IconSitemap,
  IconSparkles,
  IconSquare,
  IconSquareX,
  IconStrikethrough,
  IconSun,
  IconTable,
  IconTerminal,
  IconTerminal2,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconWorld,
  IconX,
} from '@tabler/icons-react';

export type IconComponent = ComponentType<
  SVGProps<SVGSVGElement> & {
    size?: number | string;
    stroke?: number | string;
  }
>;

export type LucideIcon = IconComponent;

export {
  IconAlertTriangle as AlertTriangle,
  IconArrowLeft as ArrowLeft,
  IconArrowsRightLeft as ArrowLeftRight,
  IconArrowsSplit2 as ArrowsSplit,
  IconArrowRight as ArrowRight,
  IconArrowUp as ArrowUp,
  IconBold as Bold,
  IconBook2 as BookOpenText,
  IconBookmark as Bookmark,
  IconBookmarkPlus as BookmarkPlus,
  IconBrandFigma as BrandFigma,
  IconBrandGithub as BrandGithub,
  IconBrandGithubFilled as BrandGithubFilled,
  IconBrandGmail as BrandGmail,
  IconBrandGoogleDrive as BrandGoogleDrive,
  IconBrandNotion as BrandNotion,
  IconBrandOpenai as BrandOpenai,
  IconBrandSlack as BrandSlack,
  IconBrandTwitter as BrandTwitter,
  IconBrandVercel as BrandVercel,
  IconBrandX as BrandX,
  IconRobot as Bot,
  IconBoxMultiple as Boxes,
  IconBrain as Brain,
  IconBug as Bug,
  IconCalendar as Calendar,
  IconCamera as Camera,
  IconChartColumn as ChartColumn,
  IconCheck as Check,
  IconCircleCheck as CheckCircle2,
  IconCheckbox as CheckSquare,
  IconChevronDown as ChevronDown,
  IconChevronLeft as ChevronLeft,
  IconChevronRight as ChevronRight,
  IconChevronUp as ChevronUp,
  IconCircle as Circle,
  IconCircleDashed as CircleDashed,
  IconGauge as CircleGauge,
  IconCircleX as CircleX,
  IconClock as Clock,
  IconCloudUpload as CloudUpload,
  IconCode as Code,
  IconCode as Code2,
  IconColumns2 as Columns2,
  IconCopy as Copy,
  IconDownload as Download,
  IconExternalLink as ExternalLink,
  IconEye as Eye,
  IconEyeOff as EyeOff,
  IconFile as File,
  IconFileDiff as FileDiff,
  IconFilePlus as FilePlus,
  IconFileText as FileText,
  IconFiles as Files,
  IconFolder as Folder,
  IconFolder as FolderClosed,
  IconFolderCode as FolderGit2,
  IconFolderOpen as FolderOpen,
  IconFolderPlus as FolderPlus,
  IconFolderSearch as FolderSearch,
  IconGitBranch as GitBranch,
  IconGitCommit as GitCommit,
  IconGitFork as GitFork,
  IconGitPullRequest as GitPullRequest,
  IconWorld as Globe,
  IconH1 as Heading1,
  IconH2 as Heading2,
  IconH3 as Heading3,
  IconHash as Hash,
  IconPhoto as Image,
  IconItalic as Italic,
  IconLayoutGrid as LayoutGrid,
  IconList as LayoutList,
  IconLink as Link,
  IconList as List,
  IconListCheck as ListChecks,
  IconListDetails as EnvironmentIcon,
  IconListNumbers as ListOrdered,
  IconListCheck as ListTodo,
  IconLoader2 as Loader2,
  IconLoader2 as LoaderCircle,
  IconMaximize as Maximize2,
  IconMessageCircle as MessageCircle,
  IconMessage as MessageSquare,
  IconMinimize as Minimize2,
  IconMinus as Minus,
  IconDeviceDesktop as Monitor,
  IconMoon as Moon,
  IconDots as MoreHorizontal,
  IconDotsVertical as MoreVertical,
  IconPalette as Palette,
  IconPaperclip as Paperclip,
  IconPencil as Pencil,
  IconPencilPlus as PencilLine,
  IconPin as Pin,
  IconPlayerPlay as Play,
  IconPlug as Plug,
  IconPlugConnected as PlugZap,
  IconPlus as Plus,
  IconQuote as Quote,
  IconArrowElbowRight as ArrowElbowRight,
  IconCornerDownRight as CornerDownRight,
  IconArrowForwardUp as Redo2,
  IconRefresh as RefreshCw,
  IconHistory as History,
  IconRotateClockwise2 as RotateCcw,
  IconScript as Script,
  IconDeviceFloppy as Save,
  IconSearch as Search,
  IconServer as Server,
  IconSettings as Settings,
  IconShieldExclamation as ShieldAlert,
  IconShieldCheck as ShieldCheck,
  IconLayoutSidebarLeftCollapse as SidebarCollapseIcon,
  IconLayoutSidebarLeftExpand as SidebarExpandIcon,
  IconAdjustmentsHorizontal as SlidersHorizontal,
  IconSparkles as Sparkles,
  IconSquare as Square,
  // 参考 Codex "New task"：方框内铅笔，用于所有"新建 task/thread"入口
  IconEdit as SquarePen,
  IconTerminal2 as SquareTerminal,
  IconLayoutSidebarRight as PanelRight,
  IconStrikethrough as Strikethrough,
  IconSun as Sun,
  IconTable as Table,
  IconTerminal as Terminal,
  IconTrash as Trash2,
  IconArrowBackUp as Undo2,
  IconUpload as Upload,
  IconUser as User,
  IconUsers as Users,
  IconSitemap as Workflow,
  IconX as X,
  IconSquareX as XSquare,
  IconBoltFilled as FastModeIcon,
  IconBolt as Zap,
  IconLayoutSidebarLeftCollapse as PanelLeft,
};

export {
  IconX as CloseIcon,
  IconCopy as CopyIcon,
  IconCheck as CheckIcon,
  IconFolder as FolderIcon,
  IconFolderOpen as FolderOpenIcon,
  IconFile as FileIcon,
  IconFileText as FileTextIcon,
  IconPhoto as ImageFileIcon,
  IconSearch as SearchIcon,
  IconTrash as TrashIcon,
  IconPin as PinIcon,
  IconSettings as SettingsIcon,
  IconPencil as EditIcon,
  IconRotateClockwise2 as RetryIcon,
  IconPaperclip as PaperclipIcon,
  IconArrowUp as ArrowUpIcon,
  IconSquare as StopIcon,
  IconChevronRight as ChevronRightIcon,
  IconChevronDown as ChevronDownIcon,
  IconChevronUp as ChevronUpIcon,
  IconDotsVertical as MoreIcon,
  IconPlus as PlusIcon,
  IconClock as ClockIcon,
  IconExternalLink as OpenIcon,
  IconFolderSearch as RevealIcon,
  IconSun as SunIcon,
  IconMoon as MoonIcon,
  IconDeviceDesktop as SystemIcon,
  IconServer as McpIcon,
  IconSettings as GeneralIcon,
  IconLayoutSidebarLeftCollapse as SidebarIcon,
  IconFilePlus as FileAddIcon,
  IconFolderPlus as FolderAddIcon,
};

/**
 * Skills glyph matching the Codex app: a tall outlined isometric box with a
 * mid-body slice (two stacked layers). No Tabler equivalent, so it is
 * hand-drawn on the same 24px grid; the finer default stroke matches the
 * reference glyph's line weight.
 */
/**
 * Fullscreen toggles matching the codex app: two bare diagonal corner
 * brackets (no arrow shafts) — outward corners to expand, inward corners to
 * collapse. No Tabler equivalent (IconArrowsDiagonal draws full arrows).
 */
export const ExpandDiagonal: IconComponent = ({ size = 24, stroke = 1.75, ...props }) =>
  createElement(
    'svg',
    {
      xmlns: 'http://www.w3.org/2000/svg',
      width: size,
      height: size,
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: stroke,
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      ...props,
    },
    createElement('path', { key: 'ne', d: 'M15 5 H19 V9' }),
    createElement('path', { key: 'sw', d: 'M9 19 H5 V15' })
  );

export const CollapseDiagonal: IconComponent = ({ size = 24, stroke = 1.75, ...props }) =>
  createElement(
    'svg',
    {
      xmlns: 'http://www.w3.org/2000/svg',
      width: size,
      height: size,
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: stroke,
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      ...props,
    },
    createElement('path', { key: 'ne', d: 'M18 10 H14 V6' }),
    createElement('path', { key: 'sw', d: 'M6 14 H10 V18' })
  );

export const SkillStack: IconComponent = ({ size = 24, stroke = 1.5, ...props }) =>
  createElement(
    'svg',
    {
      xmlns: 'http://www.w3.org/2000/svg',
      width: size,
      height: size,
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: stroke,
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      ...props,
    },
    createElement('path', { key: 'top', d: 'M12 2.5 L19 5.5 L12 8.5 L5 5.5 Z' }),
    createElement('path', { key: 'body', d: 'M5 5.5 V18.5 L12 21.5 L19 18.5 V5.5' }),
    createElement('path', { key: 'slice', d: 'M5 12 L12 15 L19 12' }),
    createElement('path', { key: 'seam', d: 'M12 8.5 V21.5' })
  );
