import assert from 'node:assert/strict';
import { SHORTCUT_COMMANDS, matchesShortcut, normalizeShortcutOverrides, shortcutFromEvent, shortcutBindings, shortcutConflict, shortcutKeycaps } from '../../src/shared/keyboard-shortcuts';
const key = (extra = {}) => ({ key: 'k', code: 'KeyK', metaKey: true, ctrlKey: false, altKey: false, shiftKey: false, isComposing: false, ...extra });
assert(matchesShortcut(key(), 'Mod+KeyK', true));
assert(!matchesShortcut(key({ shiftKey: true }), 'Mod+KeyK', true));
assert(!matchesShortcut(key({ ctrlKey: true }), 'Mod+KeyK', true));
assert(!matchesShortcut(key({ isComposing: true }), 'Mod+KeyK', true));
assert(!matchesShortcut(key({ metaKey: false, ctrlKey: true }), 'Mod+KeyK', true));
assert(matchesShortcut(key({ metaKey: false, ctrlKey: true }), 'Mod+KeyK', false));
assert(matchesShortcut(key({ key: 'Tab', code: 'Tab', metaKey: false, ctrlKey: true }), 'Ctrl+Tab', false));
assert(!matchesShortcut(key({ key: 'Tab', code: 'Tab', metaKey: false, ctrlKey: true, altKey: true }), 'Ctrl+Tab', false));
assert.equal(shortcutFromEvent(key({ key: 'Dead', code: 'KeyU', altKey: true }), true), 'Mod+Alt+KeyU');
assert.equal(shortcutFromEvent(key({ metaKey: false }), true), null);
assert.equal(shortcutFromEvent(key({ metaKey: false, altKey: true }), true), null);
assert.deepEqual(normalizeShortcutOverrides({ unknown: ['Mod+KeyA'], search: [], sidebar: ['bogus'], newTab: ['Shift+Mod+KeyT', 'Shift+Mod+KeyT'] }), { search: [], newTab: ['Mod+Shift+KeyT'] });
assert.deepEqual(shortcutBindings('search', { search: [] }), []);
assert.equal(shortcutConflict('Mod+KeyT', 'search', {}, true), 'New tab');
assert.equal(shortcutConflict('Mod+KeyC', 'search', {}, true), 'Copy');
assert.equal(shortcutConflict('Mod+Ctrl+KeyF', 'search', {}, true), 'Full screen');
assert.equal(shortcutConflict('Mod+KeyT', 'search', { newTab: [] }, true), null);
assert.equal(shortcutConflict('Ctrl+KeyT', 'search', {}, false), 'New tab');
assert.deepEqual(shortcutKeycaps('Mod+Shift+KeyK', true), ['⇧', '⌘', 'K']);
assert.deepEqual(shortcutKeycaps('Mod+Shift+KeyK', false), ['Ctrl', 'Shift', 'K']);
assert.equal(shortcutFromEvent(key({ metaKey: false, key: 'Enter', code: 'Enter', shiftKey: true }), true, true), 'Shift+Enter');
for (const mac of [true, false]) for (const command of SHORTCUT_COMMANDS) for (const binding of command.defaults) assert.equal(shortcutConflict(binding, command.id, {}, mac), null, `${command.id} must work on ${mac ? 'Mac' : 'Windows/Linux'}`);
console.log('Keyboard shortcut matching, normalization and conflicts passed');
