// Bundles the shared desktop view logic into one script for JavaScriptCore.
//   node apps/ios/core/build.mjs        (also run by the Xcode pre-build step)
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readFileSync } from "node:fs";

const here = dirname(fileURLToPath(import.meta.url));
await build({
  entryPoints: [join(here, "index.ts")],
  outfile: join(here, "../AegisKit/Sources/AegisKit/Resources/aegis-core.js"),
  bundle: true,
  // No DOM, no Node: plain JavaScriptCore on iOS 26.
  platform: "neutral",
  format: "iife",
  target: "safari18",
  minify: true,
  legalComments: "none",
  define: { "process.env.NODE_ENV": '"production"' },
  banner: { js: "/* Generated by apps/ios/core/build.mjs — do not edit. */\n" + readFileSync(join(here, "polyfills.js"), "utf8") },
  logLevel: "warning",
});
